name: Build Portable UABEA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Publish portable app
      run: dotnet publish UABEAvalonia/UABEAvalonia.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./portable_build

    - name: Create ZIP
      run: Compress-Archive -Path ./portable_build/* -DestinationPath ./UABEA_Portable.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UABEA-Portable
        path: ./UABEA_Portable.zip
